services:
  mysql:
    container_name: fr-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: farmranding123
      MYSQL_PASSWORD: farmranding123
      MYSQL_DATABASE: farmranding
    volumes:
      - ./farmranding-db/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - farmranding


networks:
  farmranding:
    driver: bridge