spring:
  config:
    activate:
      on-profile: local

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-your-key-here}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

  datasource:
    url: "jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao

server:
  port: 8081

farmranding:
  frontend-url: http://localhost:5174
