spring:
  config:
    activate:
      on-profile: local


  datasource:
    url: "jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao

server:
  port: 8081

farmranding:
  frontend-url: http://localhost:5174
