spring:
  config:
    import: optional:env.properties

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${KAKAO_CLIENT_ID}"
            client-secret: "${KAKAO_CLIENT_SECRET}"
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      api-key-verify: ${OPENAI_API_KEY_VERIFY}
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.7

springdoc:
  swagger-ui:
    path: /swagger

farmranding:
  jwt:
    secret: "${JWT_SECRET}"
    access-token-expiration: 3600000      # 1시간 (밀리초)
    refresh-token-expiration: 604800000   # 7일 (밀리초)
  gap:
    api-url: ${GAP_API_URL}
    api-key: ${GAP_API_KEY}
  api:
    standard-code:
      service-key: ${STANDARD_CODE_API_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.fr.farmranding: DEBUG

ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    api-key-verify: ${OPENAI_API_KEY_VERIFY}

address:
  csv-filename: address_20250415.csv